# Measure the percentage of code covered by tests
name: Measure Codecov

on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 3 * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: checkout@v2
      with:
        fetch-depth: ‘2’

    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: Generate Report
      run: |
        pip install coverage
        coverage run -m unittest
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
